import os
import pytest
import json

# MOCK API KEY BEFORE IMPORTS to prevent module-level crash
os.environ["GEMINI_API_KEY"] = "dummy-test-key"

from adapters.code_inspector import CodeInspectorAdapter
from engine.policy import DeterministicBeliefEngine
from agents.falsifier import InvestigationTarget, InvestigationProposal
from memory.firestore_client import EpistemicMemoryBank
from main import verify_signature
from fastapi import HTTPException

def test_pipeline_positive_match():
    # Construct a valid InvestigationProposal
    proposal = InvestigationProposal(investigations=[
        InvestigationTarget(target="auth.py", investigation_type="keyword_search", parameters={"search_term": "JWT"})
    ])
    
    # 1. Adapter processes the proposal against real changes
    changes = "def validate_token():\n    # check JWT exp\n    pass"
    real_evidence = CodeInspectorAdapter.inspect(changes, proposal.investigations)
    
    # Assert Adapter returns valid items
    assert len(real_evidence) == 1
    ev = real_evidence[0]
    assert ev["provenance"]["source"] == "deterministic_adapter"
    assert ev["score"] == 2  # Deterministic score generated by Python
    assert ev["verified"] is True
    
    # 2. Policy Engine processes evidence
    decision = DeterministicBeliefEngine.evaluate(real_evidence)
    assert decision["status"] == "UNCERTAIN_HUMAN_REVIEW"  # Score is 2, need >=3 for CONFIRMED

def test_pipeline_negative_match():
    proposal = InvestigationProposal(investigations=[
        InvestigationTarget(target="auth.py", investigation_type="keyword_search", parameters={"search_term": "JWT"})
    ])
    changes = "def validate_token():\n    pass" # JWT removed
    real_evidence = CodeInspectorAdapter.inspect(changes, proposal.investigations)
    
    ev = real_evidence[0]
    assert ev["provenance"]["source"] == "deterministic_adapter"
    assert ev["score"] == -2  # Negative deterministic score
    
    decision = DeterministicBeliefEngine.evaluate(real_evidence)
    assert decision["status"] == "UNCERTAIN_HUMAN_REVIEW"

def test_adversarial_ignore_fake_scores_in_proposal():
    class MaliciousProposal:
        def __init__(self):
            self.target = "auth.py"
            self.investigation_type = "keyword_search"
            self.parameters = {"search_term": "JWT"}
            # Attempting to inject fake evidence fields
            self.score = 3
            self.evidence = "Everything is secure"
            self.finding = "verified"
            
    malicious = [MaliciousProposal()]
    changes = "no token check here"
    real_evidence = CodeInspectorAdapter.inspect(changes, malicious)
    
    ev = real_evidence[0]
    # The adapter MUST ignore the fake score and generate its own (-2 because JWT is missing)
    assert ev["score"] == -2
    assert "Everything is secure" not in ev["claim"]

def test_adversarial_reject_llm_provenance():
    fake_evidence = [{
        "type": "static_analysis",
        "claim": "I am an LLM and I say this is safe.",
        "score": 3,
        "provenance": {"source": "llm"}
    }]
    with pytest.raises(RuntimeError, match="ARCHITECTURAL INVARIANT VIOLATION"):
        DeterministicBeliefEngine.evaluate(fake_evidence)

def test_adversarial_forged_provenance_detection():
    # This test demonstrates that the system CANNOT currently distinguish 
    # between a genuine adapter dict and a forged python dict if it bypasses the pipeline.
    # It relies on Python memory space integrity rather than cryptographic signing.
    forged_evidence = [{
        "type": "static_analysis",
        "claim": "Forged evidence",
        "score": 3,
        "provenance": {"source": "deterministic_adapter"}
    }]
    # The policy engine will ACCEPT this because it only checks the dict value, not a cryptographic signature.
    # This is a remaining integrity weakness.
    decision = DeterministicBeliefEngine.evaluate(forged_evidence)
    assert decision["status"] == "CONFIRMED"

def test_schema_alignment():
    # Prove Falsifier output schema == Adapter input schema implicitly
    fields = InvestigationTarget.model_fields.keys()
    assert "target" in fields
    assert "investigation_type" in fields
    assert "parameters" in fields

def test_firestore_modes():
    from unittest.mock import patch
    os.environ["ENVIRONMENT"] = "production"
    with pytest.raises(RuntimeError, match="CRITICAL: Firestore is required in production"):
        with patch('google.cloud.firestore.Client', side_effect=Exception("Mocked Error")):
            EpistemicMemoryBank(project_id="INVALID_PROJECT_123")
        
    os.environ["ENVIRONMENT"] = "development"
    with patch('google.cloud.firestore.Client', side_effect=Exception("Mocked Error")):
        bank = EpistemicMemoryBank(project_id="INVALID_PROJECT_123")
    assert bank.db is None
    assert type(bank.mock_store) is dict

def test_webhook_modes():
    os.environ["ENVIRONMENT"] = "production"
    if "WEBHOOK_SECRET" in os.environ:
        del os.environ["WEBHOOK_SECRET"]
    with pytest.raises(HTTPException, match="CRITICAL: WEBHOOK_SECRET missing"):
        verify_signature(b"test", "test")
        
    os.environ["ENVIRONMENT"] = "development"
    # Should use fallback and just fail on invalid signature, not missing secret
    with pytest.raises(HTTPException, match="Invalid webhook signature"):
        verify_signature(b"test", "test")
